"use client";
import {FormEvent,useState} from "react"; import {useRouter} from "next/navigation";
function youtubeId(v:string){const s=v.trim();const m=s.match(/(?:v=|youtu\.be\/|embed\/)([A-Za-z0-9_-]{6,})/);return m?.[1]||s;}
function PartEditor({p}:{p:any}){const router=useRouter();const [x,setX]=useState({...p});const [busy,setBusy]=useState(false);async function save(){setBusy(true);const r=await fetch('/api/admin/parts',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...x,video_ref:youtubeId(x.video_ref)})});setBusy(false);if(r.ok)router.refresh();else alert('บันทึก Part ไม่สำเร็จ');}async function del(){if(!confirm('ลบ Part นี้? Progress ของ Part นี้จะถูกลบตามไปด้วย'))return;const r=await fetch('/api/admin/parts',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id})});if(r.ok)router.refresh();else alert('ลบ Part ไม่สำเร็จ');}return <div className="card quiz-question"><div className="space"><strong>Part {x.order_no}</strong><div className="inline"><button className="ghost-btn" onClick={save} disabled={busy}>บันทึก</button><button className="btn btn-danger" onClick={del}>ลบ</button></div></div><div className="form-row"><div className="field"><label>ลำดับ</label><input type="number" min="1" value={x.order_no} onChange={e=>setX({...x,order_no:Number(e.target.value)})}/></div><div className="field"><label>ชื่อ Part</label><input value={x.title} onChange={e=>setX({...x,title:e.target.value})}/></div></div><div className="field"><label>YouTube URL / ID</label><input value={x.video_ref} onChange={e=>setX({...x,video_ref:e.target.value})}/></div><div className="field"><label>รายละเอียด</label><textarea value={x.description} onChange={e=>setX({...x,description:e.target.value})}/></div></div>}
export default function CourseEditor({course,parts,users,enrollments}:{course:any,parts:any[],users:any[],enrollments:any[]}){
 const router=useRouter(); const [msg,setMsg]=useState('');
 async function updateCourse(e:FormEvent<HTMLFormElement>){e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch(`/api/admin/courses/${course.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});setMsg(r.ok?'บันทึกคอร์สแล้ว':'บันทึกไม่สำเร็จ');router.refresh();}
 async function addPart(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const b:any=Object.fromEntries(f.entries());b.course_id=course.id;b.video_ref=youtubeId(String(b.video_ref||''));const r=await fetch('/api/admin/parts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});if(r.ok){(e.currentTarget as HTMLFormElement).reset();router.refresh();}else setMsg('เพิ่ม Part ไม่สำเร็จ');}
 async function resetAll(){if(!confirm('รีเซ็ตผู้เรียนทุกคนในคอร์สนี้? ประวัติรอบเดิมจะยังถูกเก็บไว้'))return;await fetch('/api/admin/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:'all',course_id:course.id})});router.refresh();}
 async function enroll(uid:string){await fetch('/api/admin/enrollments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:uid,course_id:course.id})});router.refresh();}
 async function resetOne(uid:string){if(!confirm('รีเซ็ตผู้เรียนคนนี้ในคอร์สนี้?'))return;await fetch('/api/admin/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope:'user',user_id:uid,course_id:course.id})});router.refresh();}
 const enrolled=new Map(enrollments.map(x=>[x.user_id,x]));
 return <div className="two-col">
  <section className="card panel"><div className="eyebrow">COURSE SETTINGS</div><h3>ข้อมูลคอร์ส</h3>{msg&&<div className="alert success">{msg}</div>}
   <form onSubmit={updateCourse}><div className="form-row"><div className="field"><label>Code</label><input name="code" defaultValue={course.code}/></div><div className="field"><label>เกณฑ์เรียนผ่าน (%)</label><input name="passing_progress" type="number" min="1" max="100" defaultValue={course.passing_progress}/></div></div><div className="field"><label>ชื่อคอร์ส</label><input name="title" defaultValue={course.title}/></div><div className="field"><label>รายละเอียด</label><textarea name="description" defaultValue={course.description}/></div><div className="inline"><label className="badge"><input type="checkbox" name="is_published" defaultChecked={course.is_published}/> Published</label><button className="btn">บันทึก</button></div></form>
   <div className="divider"/><h3>เพิ่มวิดีโอ / Part</h3><form onSubmit={addPart}><div className="form-row"><div className="field"><label>ลำดับ</label><input name="order_no" type="number" min="1" defaultValue={parts.length+1}/></div><div className="field"><label>ชื่อ Part</label><input name="title" required/></div></div><div className="field"><label>YouTube URL หรือ Video ID</label><input name="video_ref" required placeholder="https://youtu.be/..."/></div><div className="field"><label>รายละเอียด Part</label><textarea name="description"/></div><button className="btn">เพิ่ม Part</button></form>
   {parts.length>0&&<><div className="divider"/><h3>แก้ไข Part / วิดีโอ</h3>{parts.map(p=><PartEditor p={p} key={p.id}/>)}</>}
  </section>
  <section className="card panel"><div className="space"><div><div className="eyebrow">ENROLLMENT</div><h3>ผู้เรียน</h3></div><button className="btn btn-danger" onClick={resetAll}>Reset ทั้งคอร์ส</button></div><div className="table-wrap"><table className="table"><thead><tr><th>ผู้เรียน</th><th>สถานะ</th><th></th></tr></thead><tbody>{users.map(u=>{const en=enrolled.get(u.id);return <tr key={u.id}><td>{u.first_name} {u.last_name}<br/><span className="muted small">{u.student_id||u.email}</span></td><td>{en?<span className="badge good">Enrolled · รอบ {en.reset_count+1}</span>:<span className="badge">ยังไม่ลง</span>}</td><td>{en?<button className="ghost-btn" onClick={()=>resetOne(u.id)}>Reset</button>:<button className="ghost-btn" onClick={()=>enroll(u.id)}>Enroll</button>}</td></tr>})}</tbody></table></div></section>
 </div>
}
