"use client";
import {FormEvent,useState} from "react";import {useRouter} from "next/navigation";
type Q={id?:string,question_text:string,option_a:string,option_b:string,option_c:string,option_d:string,correct_option:string,order_no:number};
const blank=(n:number):Q=>({question_text:'',option_a:'',option_b:'',option_c:'',option_d:'',correct_option:'',order_no:n});

function ExistingQuestion({q}:{q:any}){const router=useRouter();const [x,setX]=useState<any>(q);const [busy,setBusy]=useState(false);async function save(){setBusy(true);const r=await fetch('/api/admin/quiz/questions',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(x)});setBusy(false);if(r.ok)router.refresh();else alert('บันทึกไม่สำเร็จ');}async function del(){if(!confirm('ลบข้อสอบข้อนี้?'))return;const r=await fetch('/api/admin/quiz/questions',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:q.id})});if(r.ok)router.refresh();else alert('ลบไม่สำเร็จ');}return <div className="card quiz-question"><div className="space"><strong>ข้อ {x.order_no}</strong><div className="inline"><button className="ghost-btn" onClick={save} disabled={busy}>บันทึก</button><button className="btn btn-danger" onClick={del}>ลบ</button></div></div><div className="field"><label>คำถาม</label><textarea value={x.question_text} onChange={e=>setX({...x,question_text:e.target.value})}/></div>{(['a','b','c','d'] as const).map(k=><div className="field" key={k}><label>{k.toUpperCase()}</label><input value={x[`option_${k}`]} onChange={e=>setX({...x,[`option_${k}`]:e.target.value})}/></div>)}<div className="field"><label>คำตอบถูก</label><select value={x.correct_option} onChange={e=>setX({...x,correct_option:e.target.value})}><option>A</option><option>B</option><option>C</option><option>D</option></select></div></div>}

export default function QuizImportEditor({courseId,questions}:{courseId:string,questions:any[]}){const router=useRouter();const [draft,setDraft]=useState<Q[]>([]);const [msg,setMsg]=useState('');
 async function importPdf(e:FormEvent<HTMLFormElement>){e.preventDefault();setMsg('');const fd=new FormData(e.currentTarget);fd.append('course_id',courseId);const r=await fetch('/api/admin/quiz/import-pdf',{method:'POST',body:fd});const j=await r.json();if(!r.ok)return setMsg(j.error||'อ่าน PDF ไม่สำเร็จ');setDraft(j.questions||[]);setMsg(`ตรวจพบ ${j.questions?.length||0} ข้อ กรุณาตรวจและกำหนดคำตอบก่อนบันทึก`);}
 function set(i:number,k:keyof Q,v:any){setDraft(d=>d.map((q,n)=>n===i?{...q,[k]:v}:q));}
 function addManual(){setDraft(d=>[...d,blank(questions.length+d.length+1)]);}
 async function save(){const r=await fetch('/api/admin/quiz/questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({course_id:courseId,questions:draft})});const j=await r.json();if(!r.ok)return setMsg(j.error||'บันทึกไม่สำเร็จ');setDraft([]);setMsg('บันทึกข้อสอบแล้ว');router.refresh();}
 return <section className="card panel"><div className="space"><div><div className="eyebrow">POST-TEST BUILDER</div><h3>ข้อสอบท้ายคอร์ส</h3></div><button className="btn btn-secondary" onClick={addManual}>+ เพิ่มข้อด้วยตนเอง</button></div><div className="two-col"><div><form onSubmit={importPdf}><div className="field"><label>นำเข้าข้อสอบ PDF</label><input type="file" name="file" accept="application/pdf" required/></div><button className="btn">อ่าน PDF และจัดรูปแบบ</button></form><p className="footer-note">ระบบพยายามแยก “เลขข้อ + 4 ตัวเลือก” อัตโนมัติ แต่จะไม่เดาคำตอบถูกเพื่อป้องกันความผิดพลาด Admin ต้อง Preview/แก้ไข/เลือก A–D ก่อน Save</p></div><div><strong>ข้อสอบปัจจุบัน {questions.length} ข้อ</strong><p className="muted small">แก้ไขหรือลบแต่ละข้อได้ด้านล่าง</p></div></div>{msg&&<div className="alert success">{msg}</div>}{draft.length>0&&<><div className="divider"/><h3>Preview / New questions</h3>{draft.map((q,i)=><div className="card quiz-question" key={i}><div className="space"><strong>ข้อใหม่ {i+1}</strong><button className="ghost-btn" onClick={()=>setDraft(d=>d.filter((_,n)=>n!==i))}>เอาออก</button></div><div className="field"><label>คำถาม</label><textarea value={q.question_text} onChange={e=>set(i,'question_text',e.target.value)}/></div>{(['a','b','c','d'] as const).map(x=><div className="field" key={x}><label>{x.toUpperCase()}</label><input value={(q as any)[`option_${x}`]} onChange={e=>set(i,`option_${x}` as keyof Q,e.target.value)}/></div>)}<div className="field"><label>คำตอบที่ถูก</label><select value={q.correct_option||''} onChange={e=>set(i,'correct_option',e.target.value)} required><option value="">เลือกคำตอบ</option><option>A</option><option>B</option><option>C</option><option>D</option></select></div></div>)}<button className="btn" onClick={save} disabled={draft.some(q=>!q.correct_option||!q.question_text||!q.option_a||!q.option_b||!q.option_c||!q.option_d)}>บันทึกข้อใหม่ทั้งหมด</button></>}{questions.length>0&&<><div className="divider"/><h3>แก้ไขข้อสอบปัจจุบัน</h3>{questions.map(q=><ExistingQuestion key={q.id} q={q}/>)}</>}</section>}
