"use client";
import {useEffect,useState} from "react";import Link from "next/link";
type Q={id:string,prompt:string,options:{key:string,text:string}[]};
export default function QuizClient({courseId}:{courseId:string}){const [loading,setLoading]=useState(true);const [questions,setQuestions]=useState<Q[]>([]);const [answers,setAnswers]=useState<Record<string,string>>({});const [error,setError]=useState('');const [result,setResult]=useState<any>(null);const [submitting,setSubmitting]=useState(false);
 useEffect(()=>{fetch(`/api/quiz/${courseId}`).then(async r=>({ok:r.ok,j:await r.json()})).then(({ok,j})=>{if(!ok)setError(j.error||'เปิดข้อสอบไม่ได้');else if(j.status==='submitted')setResult(j);else setQuestions(j.questions||[]);setLoading(false)}).catch(()=>{setError('เชื่อมต่อข้อสอบไม่ได้');setLoading(false)});},[courseId]);
 async function submit(){if(Object.keys(answers).length!==questions.length)return setError('กรุณาตอบให้ครบทุกข้อก่อนส่ง');if(!confirm('ยืนยันส่งคำตอบ? หลังส่งแล้วจะไม่สามารถทำซ้ำได้จนกว่า Admin จะ Reset'))return;setSubmitting(true);setError('');const r=await fetch(`/api/quiz/${courseId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})});const j=await r.json();setSubmitting(false);if(!r.ok)return setError(j.error||'ส่งคำตอบไม่สำเร็จ');setResult(j);}
 if(loading)return <div className="card panel">กำลังเตรียมข้อสอบและสุ่มลำดับ...</div>;
 if(error&&!questions.length&&!result)return <div className="card panel"><div className="alert">{error}</div><Link className="btn btn-secondary" href="/dashboard">กลับ Dashboard</Link></div>;
 if(result)return <section className="card panel" style={{textAlign:'center',padding:40}}><div className="eyebrow">RESULT</div><h2 style={{fontSize:54,margin:'12px 0'}}>{Number(result.score).toFixed(0)}%</h2><p className="muted">ตอบถูก {result.correct_answers} จาก {result.total_questions} ข้อ</p><div className="alert success">บันทึกผลสอบแล้ว หากต้องการทำใหม่ ผู้ดูแลระบบต้อง Reset รอบการเรียนก่อน</div><Link className="btn" href="/dashboard">กลับ Dashboard</Link></section>;
 return <><div className="alert">ข้อสอบถูกสุ่มทั้งลำดับข้อและลำดับตัวเลือก ระบบจะบันทึกผลเมื่อกด “ส่งคำตอบ” เพียงครั้งเดียว</div>{questions.map((q,i)=><section className="card quiz-question" key={q.id}><div className="eyebrow">QUESTION {i+1} / {questions.length}</div><h3>{q.prompt}</h3><div className="options">{q.options.map(o=><label className="option" key={o.key}><input type="radio" name={q.id} checked={answers[q.id]===o.key} onChange={()=>setAnswers(a=>({...a,[q.id]:o.key}))}/><span>{o.text}</span></label>)}</div></section>)}{error&&<div className="alert">{error}</div>}<div className="space"><span className="muted small">ตอบแล้ว {Object.keys(answers).length}/{questions.length} ข้อ</span><button className="btn" onClick={submit} disabled={submitting}>{submitting?'กำลังบันทึก...':'ส่งคำตอบ'}</button></div></>;
}
